name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Update manifest.json with version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Updating manifest.json with version $VERSION"
          jq --arg version "$VERSION" '.version = $version' custom_components/elektronny_gorod/manifest.json > tmp.json && mv tmp.json custom_components/elektronny_gorod/manifest.json

      - name: Prepare release
        run: |
          cd ${{ github.workspace }}/custom_components/elektronny_gorod
          zip -r elektronny_gorod.zip ./

      - name: Upload zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{ github.workspace }}/custom_components/elektronny_gorod/elektronny_gorod.zip
          asset_name: elektronny_gorod.zip
          overwrite: true

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: custom_components/elektronny_gorod/manifest.json
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Update manifest.json to version ${{ github.event.release.tag_name }}
          push: -u origin master